[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags = 
    -DCORE_DEBUG_LEVEL=1
    -finput-charset=UTF-8

board_build.partitions = huge_app.csv

lib_deps =
    knolleary/PubSubClient @ ^2.8
    https://github.com/voicevon/esp32_wifi_mqtt_manager.git
    paulstoffregen/OneWire @ ^2.3.8
    bblanchon/ArduinoJson @ ^6.21.3
